name: plgx-agent 
base: core20 
version: '0.1' 
summary: plgx agent for linux as snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
environment:
  FLAG_FILE: $SNAP_COMMON/etc/plgx_osquery/osquery.flags
  CONFIG_FILE: $SNAP_COMMON/etc/plgx_osquery/osquery.conf"
  LOCAL_PIDFILE: $SNAP_COMMON/var/plgx_osquery/osqueryd.pidfile"
  PIDFILE: $SNAP_COMMON/var/run/plgx_osqueryd.pidfile"
apps:
  plgx-osqueryctl: 
    command: usr/bin/plgx_osqueryctl
  plgx-osqueryd:
    command: usr/bin/plgx_osqueryd --flagfile $FLAG_FILE

parts:
  exec:
    # See 'snapcraft plugins'
    plugin: dump
    source: x64
    stage:
      - usr/bin/plgx_osqueryd
      - usr/bin/plgx_osqueryctl
      - etc/plgx_osquery/osquery.flags
      - etc/plgx_osquery/certificate.crt
      - etc/plgx_osquery/secret.txt
      - etc/plgx_osquery/osquery.conf
      - usr/share/plgx_osquery/osquery.example.conf
      - etc/plgx_osquery/extensions.load
      - usr/bin/plgx_linux_extension.ext
    organize:
      plgx_osqueryd: usr/bin/plgx_osqueryd
      plgx_osqueryctl: usr/bin/plgx_osqueryctl
      osquery.flags: etc/plgx_osquery/osquery.flags
      certificate.crt: etc/plgx_osquery/certificate.crt
      secret.txt: etc/plgx_osquery/secret.txt
      # plgx_osqueryd.initd: usr/bin/plgx_osqueryd.initd
      # plgx_osqueryd.service: usr/bin/plgx_osqueryd.service
      # plgx_osqueryd.sysconfig: usr/bin/plgx_osqueryd.sysconfig
      osquery.conf: etc/plgx_osquery/osquery.conf
      osquery.example.conf: usr/share/plgx_osquery/osquery.example.conf
      extensions.load: etc/plgx_osquery/extensions.load
      plgx_linux_extension.ext: usr/bin/plgx_linux_extension.ext
      
    prime:
      - usr/bin
      - etc/plgx_osquery
      - usr/share/plgx_osquery
    
    override-build: |
      snapcraftctl build
      chmod 0755 $SNAPCRAFT_PART_INSTALL/plgx_osqueryctl
      chmod 0755 $SNAPCRAFT_PART_INSTALL/plgx_osqueryd
      chmod 0755 $SNAPCRAFT_PART_INSTALL/plgx_linux_extension.ext

    
